version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    assignees:
      - ysashank
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    assignees:
      - ysashank
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
